kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-data-pvc
  namespace: sapd
spec:
  storageClassName: your-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
